apiVersion: v1
kind: Service
metadata:
  labels:
    app: test1
  name: test1
spec:
  type: NodePort
  ports:
  - name: "test1-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: test1
  